### ISSUE TITLE
There are some errors in the phase of dependency analysis

### ISSUE THREAD

**Issue by Amocy-Wang** [aspire-project/chisel#6]
Consider the following case, I want to reduce all tokens in the following code and the test function will be always true.
```
int A(int a) {
 return a;
}

int B(int b){
 return b;
}

int main() {
 int a=1,b=2,c=3,d=4;
 b=a+1;
 c=a+b;
 d=a+b+c;
 return B(A(0));
}
```
The ideal output file will be an empty file because the test script returns true for each testing and CHISEL will remove each single token in the original file. However, CHISEL doesn't remove any token. Further, we check the source code in CHISEL and we found that the def-use analysis may be buggy. Next, we run CHISEL with --skip_local_dep and --skip_global_dep to disable the buggy analysis and CHISEL returns the ideal output.

**Comment by ppashakhanloo** [comment]
Hi Guancheng!

Thanks for trying out our Chisel!

Let me clarify some details. There are some "hard rules" that Chisel uses when local or global dependency is enabled. When you turn these dependency analyses off, these hard rules are no longer applied. In this case, the hard rule that prevents the removal of the functions is "keeping the main function". Therefore,
```
int main() {
 int a=1,b=2,c=3,d=4;
 b=a+1;
 c=a+b;
 d=a+b+c;
 return B(A(0));
}
```
is kept. Another hard rule is that, a function that is not `void`, must have at least one return-statement. Therefore, `return B(A(0));` is kept in the main function. Additionally, Chisel does not make changes to elements smaller than statements in order to keep the naturalness of programs; so, `B(A(0))` is kept as is. So both `A()` and `B()` function definitions are kept as a result.

The above is an example an implementation decision that we made but it can be improved by finer-grained debloating. We welcome any pull requests that you might make to improve Chisel!
